name: Run test after push

on:
  push:
    branches: [ "master" ]


jobs:
  run_unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install cunit
        run: sudo apt-get install -y libcunit1 libcunit1-doc libcunit1-dev

      - name: run test
        run: make runtests
